language: java
sudo: false

# Skip the default Maven command launched by Travis.
install: true

# Test several JDK.
matrix:
  include:
    - jdk: openjdk8
      env: BUILD_CMD="mvn clean install cobertura:cobertura coveralls:report -DrepoToken=${COVERALLS_TOKEN}"
    - jdk: oraclejdk8
      env: BUILD_CMD="mvn clean install"
    - jdk: oraclejdk9
      env: BUILD_CMD="mvn clean install"

# Build with Maven.
script: eval $BUILD_CMD
